
// Generated by ntoolkit/futures
package futures_test

import "ntoolkit/futures"

import "testing"


type DeferredValueT struct {
	DeferredValue futures.Promise
}

func (promise *DeferredValueT) init() {
	if promise.DeferredValue == nil {
		promise.DeferredValue = &futures.DeferredValue{}
	}
}

func (promise *DeferredValueT) Resolve(result *testing.T) {
	promise.init()
	promise.DeferredValue.PResolve(result)
}

func (promise *DeferredValueT) Reject(err error) {
	promise.init()
	promise.DeferredValue.PReject(err)
}

func (promise *DeferredValueT) Errors() []error {
	promise.init()
	return promise.DeferredValue.PErrors()
}

func (promise *DeferredValueT) Then(resolve func(*testing.T), reject func(error)) *DeferredValueT {
	promise.init()
	promise.DeferredValue.PThen(func(value interface{}) {
		if v, ok := value.(*testing.T); ok {
			resolve(v)
		}
		panic("Invalid value used to resolve DeferredValueT")
	}, reject)
	return promise
}

func (promise *DeferredValueT) PThen(result func(interface{}), reject func(error)) futures.Promise {
	promise.init()
	return promise.DeferredValue.PThen(result, reject)
}

func (promise *DeferredValueT) PErrors() []error {
	promise.init()
	return promise.DeferredValue.PErrors()
}

func (promise *DeferredValueT) PResolve(result interface{}) {
	promise.init()
	promise.DeferredValue.PResolve(result)
}

func (promise *DeferredValueT) PReject(err error) {
	promise.init()
	promise.DeferredValue.PReject(err)
}
